version: "3"

services:
  database:
    image: mysql
    logging:
      driver: none
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: supplier_db

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password

  backend:
    build:
      context: apps/backend
    command: sh -c "npm run dev"
    volumes:
      - ./apps/backend:/server
    environment:
      DB_HOST: database
      DB_USERNAME: root
      DB_NAME: supplier_db
      DB_PASSWORD: password

    depends_on:
      database:
        condition: service_healthy

    ports:
      - "8080:8080"

    tty: true
    stdin_open: true

  frontend:
    build:
      context: apps/frontend
    command: sh -c "npm run dev"
    volumes:
      - ./apps/frontend:/server
    ports:
      - 3000:3000
